"""Pydantic v2 schemas for Risk2Relief."""

from app.schemas.common import PaginationParams, PaginatedResponse, ErrorDetail
from app.schemas.health import HealthResponse, DependencyHealth
from app.schemas.simulation import (
    SimulationStatusResponse,
    SafetyBoundaryStatus,
    SimulationExecuteRequest,
    SimulationRunResponse,
    SimulationRunDetailResponse,
    SafetyEventResponse,
)
from app.schemas.building import (
    BuildingCreate,
    BuildingUpdate,
    BuildingResponse,
    BuildingHierarchyResponse,
    FloorCreate,
    FloorResponse,
    ZoneCreate,
    ZoneResponse,
)
from app.schemas.node import (
    NodeTypeEnum,
    AntiGravityNodeStateEnum,
    StructuralNodeCreate,
    StructuralNodeResponse,
    AntiGravityNodeCreate,
    AntiGravityNodeResponse,
)
from app.schemas.telemetry import (
    SourceTypeEnum,
    QualityEnum,
    TelemetrySourceCreate,
    TelemetrySourceResponse,
    TelemetryReadingCreate,
    TelemetryReadingResponse,
    TelemetryBatchCreate,
    TelemetryBatchResponse,
    TelemetryQualityResponse,
    TelemetryFilterParams,
)
from app.schemas.configuration import (
    ScenarioTypeEnum,
    BuildingConfigCreate,
    BuildingConfigResponse,
    GravityConfigCreate,
    GravityConfigResponse,
    SafetyThresholdCreate,
    SafetyThresholdResponse,
    EnvironmentalConfigCreate,
    EnvironmentalConfigResponse,
    SimulationScenarioCreate,
    SimulationScenarioResponse,
)
from app.schemas.safety import (
    SafetyStateTransitionRequest,
    SafetyStateTransitionResponse,
    IncidentCreate,
    IncidentUpdate,
    IncidentResponse,
    FailureInjectionRequest,
    FailureInjectionResponse,
)
from app.schemas.reports import (
    ReportTypeEnum,
    ReportGenerateRequest,
    ReportResponse,
    ReportSection,
)
from app.schemas.environmental import (
    EnvironmentalStateResponse,
    EnvironmentalAssessRequest,
    EnvironmentalAssessResponse,
)
from app.schemas.auth import (
    RoleEnum,
    LoginRequest,
    RefreshTokenRequest,
    Token,
    TokenPayload,
    UserCreate,
    UserResponse,
    UserProfileResponse,
)
from app.schemas.audit import (
    AuditLogResponse,
    AuditLogFilterParams,
)

__all__ = [
    "PaginationParams",
    "PaginatedResponse",
    "ErrorDetail",
    "HealthResponse",
    "DependencyHealth",
    "SimulationStatusResponse",
    "SafetyBoundaryStatus",
    "SimulationExecuteRequest",
    "SimulationRunResponse",
    "SimulationRunDetailResponse",
    "SafetyEventResponse",
    "BuildingCreate",
    "BuildingUpdate",
    "BuildingResponse",
    "BuildingHierarchyResponse",
    "FloorCreate",
    "FloorResponse",
    "ZoneCreate",
    "ZoneResponse",
    "NodeTypeEnum",
    "AntiGravityNodeStateEnum",
    "StructuralNodeCreate",
    "StructuralNodeResponse",
    "AntiGravityNodeCreate",
    "AntiGravityNodeResponse",
    "SourceTypeEnum",
    "QualityEnum",
    "TelemetrySourceCreate",
    "TelemetrySourceResponse",
    "TelemetryReadingCreate",
    "TelemetryReadingResponse",
    "TelemetryBatchCreate",
    "TelemetryBatchResponse",
    "TelemetryQualityResponse",
    "TelemetryFilterParams",
    "ScenarioTypeEnum",
    "BuildingConfigCreate",
    "BuildingConfigResponse",
    "GravityConfigCreate",
    "GravityConfigResponse",
    "SafetyThresholdCreate",
    "SafetyThresholdResponse",
    "EnvironmentalConfigCreate",
    "EnvironmentalConfigResponse",
    "SimulationScenarioCreate",
    "SimulationScenarioResponse",
    "SafetyStateTransitionRequest",
    "SafetyStateTransitionResponse",
    "IncidentCreate",
    "IncidentUpdate",
    "IncidentResponse",
    "FailureInjectionRequest",
    "FailureInjectionResponse",
    "ReportTypeEnum",
    "ReportGenerateRequest",
    "ReportResponse",
    "ReportSection",
    "EnvironmentalStateResponse",
    "EnvironmentalAssessRequest",
    "EnvironmentalAssessResponse",
    "RoleEnum",
    "LoginRequest",
    "RefreshTokenRequest",
    "Token",
    "TokenPayload",
    "UserCreate",
    "UserResponse",
    "UserProfileResponse",
    "AuditLogResponse",
    "AuditLogFilterParams",
]
